### ISSUE TITLE
blue is not detecting in low light conditions

### ISSUE THREAD

**Issue by leonoosterwijk** [dwalton76/rubiks-color-resolver#1]
hey i found this project tonight and tried to make it work on my raspberry pi (for my rubiks solving robot) and i found that in low light the blue on my cube is not being detected. I tried fiddling with the blue definitions in the file but might not have the right end of the stick. here is the image which is failing detection let me know if you have any advice. 
<img width="740" alt="screen shot 2017-03-11 at 23 22 45" src="https://cloud.githubusercontent.com/assets/845159/23829223/ff56103a-06b1-11e7-93a0-8cc92c18122a.png">

**Comment by dwalton76** [comment]
@leonoosterwijk when it happens can you capture an image (just straight from the webcam, not from the program with the white circles) and post it here?  You can run "rubiks-cube-tracker.py --filename FILENAME.png" and it will pop up a few windows at various stages to show what is happening.  My guess is that there blue vs. black surroundings are so close that we aren't find the edges of the blue squares. 

PS
This part of the code is actually part of https://github.com/dwalton76/rubiks-cube-tracker so we should probably move the conversation there
