### ISSUE TITLE
bug/No such file or directory

### ISSUE THREAD

**Issue by Safacan7** [dwalton76/rubiks-color-resolver#9]
Hi when I run my python3, all sides are scanned and an output (JSON) file is also created, however this issue pops up before it starts solving it.

![image](https://user-images.githubusercontent.com/83445170/156988489-79e5328b-c7a4-4d9f-8e56-1ecc56d77fad.png)

Could you help please!

**Comment by dwalton76** [comment]
Hello, can you attach the JSON file?

**Comment by Safacan7** [comment]
I can't attach the file but this is the output

`{"5": [255, 255, 255], "9": [36, 255, 255], "6": [109, 255, 255], "3": [218, 255, 255], "2": [255, 255, 255], "1": [218, 255, 127], "4": [72, 255, 255], "7": [182, 255, 127], "8": [255, 255, 255], "23": [255, 255, 255], "27": [255, 255, 255], "24": [255, 255, 255], "21": [255, 255, 255], "20": [109, 255, 255], "19": [36, 255, 255], "22": [255, 255, 255], "25": [255, 255, 255], "26": [255, 255, 255], "50": [255, 255, 255], "54": [255, 255, 255], "51": [72, 255, 255], "48": [255, 255, 255], "47": [109, 255, 255], "46": [145, 255, 255], "49": [255, 255, 255], "52": [36, 255, 255], "53": [72, 255, 255], "14": [109, 255, 255], "10": [218, 255, 255], "13": [218, 255, 255], "16": [218, 255, 255], "17": [182, 170, 255], "18": [72, 255, 255], "15": [109, 255, 255], "12": [255, 255, 127], "11": [255, 255, 127], "41": [255, 255, 255], "43": [255, 255, 255], "44": [255, 255, 255], "45": [255, 255, 255], "42": [255, 255, 255], "39": [109, 255, 255], "38": [255, 255, 255], "37": [255, 255, 255], "40": [255, 255, 255], "32": [109, 255, 255], "34": [72, 255, 255], "35": [255, 255, 255], "36": [109, 255, 255], "33": [72, 255, 255], "30": [72, 255, 255], "29": [255, 255, 255], "28": [145, 85, 127], "31": [255, 255, 255]}`


![image](https://user-images.githubusercontent.com/83445170/157037959-c88a962c-95ef-44dd-acc2-c76d2f8d8adb.png)

**Comment by dwalton76** [comment]
@Safacan7 sorry for being slow to respond.  I think I see the issue....I suspect windows behaves differently when python opens a file in `a` mode with the file is not there.

**Comment by dwalton76** [comment]
@Safacan7 I just pushed a fix, do `git pull` to pick it up

**Comment by Safacan7** [comment]
Thank you!
